# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# site overview stuff
title: Semesterarbeit 3
subtitle: Marco Kälin & Dennis Buathong
email: marco.kaelin1@edu.tbz.ch / dennis.buathong@edu.tbz.ch
description: >- # this means to ignore newlines until another declaration
  This site is used by Euthal02 and Bazzako as their documentation place for their third Semester Thesis.

# personal stuff
author: "Marco Kälin & Dennis Buathon"
github_username:  "Euthal02 & Bazzako"

# external stuff
aux_links:
  Projektplanung: https://github.com/users/Euthal02/projects/4
  Git Repo: https://github.com/Euthal02/SemArb3_WeatherAPI
aux_links_new_tab: true


# technical site stuff
url: "https://euthal02.github.io/SemArb3_WeatherAPI/"
logo: "/ressources/images/general/logo.jpg"
favicon_ico: "/ressources/images/general/favicon.ico"
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
  - jekyll-feed
back_to_top: true
back_to_top_text: "Back to top"
#color_scheme: dark
callouts:
  information:
    title: Information
    color: blue


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
